[package]
name = "nes256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.6.0"
lazy_static = "1.5.0"
num = "0.4.3"
